"""Сборщик ноутбуков 09–11 (главы 2 и 3 ВКР).

Создаёт три ipynb-файла через nbformat, чтобы избежать
ручной правки JSON. Запуск:

    python scripts/build_chapter_notebooks.py
"""

from __future__ import annotations

from pathlib import Path

import nbformat as nbf

ROOT = Path(__file__).resolve().parents[1]
NB_DIR = ROOT / "notebooks"


def md(text: str) -> nbf.NotebookNode:
    return nbf.v4.new_markdown_cell(text)


def code(text: str) -> nbf.NotebookNode:
    return nbf.v4.new_code_cell(text)


def write_notebook(name: str, cells: list[nbf.NotebookNode]) -> Path:
    nb = nbf.v4.new_notebook()
    nb["cells"] = cells
    nb["metadata"] = {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "name": "python",
            "version": "3.10",
        },
    }
    path = NB_DIR / name
    nbf.write(nb, path)
    return path


# =============================================================== Notebook 09
def build_09() -> Path:
    cells = [
        md(
            "# 09 — Разведочный анализ датасета (Глава 2 ВКР)\n\n"
            "Описание датасета для раздела 2.3.2 «Алгоритм подготовки данных». "
            "Все графики сохраняются в `reports/figures/dataset/` с DPI=300; "
            "подписи на русском, шрифт **DejaVu Sans**.\n\n"
            "### Что считаем\n"
            "1. Сводная таблица: размер каждого split, доли v3.1/v4.0, доли d_ru, "
            "EPSS/KEV/exploit.\n"
            "2. Распределение по источникам (NVD vs БДУ ФСТЭК) — pie chart.\n"
            "3. Дисбаланс классов по 12 метрикам CVSS v4.0 — 3×4 grid bar plots.\n"
            "4. Длины описаний в токенах (en/ru — overlay).\n"
            "5. Распределение итоговых CVSS-баллов и severity (Critical/.../None).\n"
            "6. Топ-20 наиболее частых CWE в train set.\n"
            "7. Корреляции между метриками v4.0 (Cramer's V heatmap).\n"
        ),
        code(
            "from pathlib import Path\n"
            "import sys\n"
            "\n"
            "import numpy as np\n"
            "import pandas as pd\n"
            "import matplotlib.pyplot as plt\n"
            "import seaborn as sns\n"
            "\n"
            "ROOT = Path.cwd()\n"
            "if ROOT.name == 'notebooks':\n"
            "    ROOT = ROOT.parent\n"
            "sys.path.insert(0, str(ROOT))\n"
            "\n"
            "plt.rcParams['font.family'] = 'DejaVu Sans'\n"
            "plt.rcParams['figure.dpi'] = 100\n"
            "plt.rcParams['savefig.dpi'] = 300\n"
            "plt.rcParams['savefig.bbox'] = 'tight'\n"
            "\n"
            "FIG_DIR = ROOT / 'reports' / 'figures' / 'dataset'\n"
            "FIG_DIR.mkdir(parents=True, exist_ok=True)\n"
            "print('Figures →', FIG_DIR)"
        ),
        md("## 1. Загрузка train/val/test и сводная статистика"),
        code(
            "splits = {}\n"
            "for name in ['train', 'val', 'test']:\n"
            "    splits[name] = pd.read_parquet(ROOT / 'data' / 'processed' / f'{name}.parquet')\n"
            "    print(f'{name}: {len(splits[name]):,} строк')"
        ),
        code(
            "def split_stats(df: pd.DataFrame) -> dict:\n"
            "    n = len(df)\n"
            "    v3 = df['cvss_v3_vector'].notna().sum()\n"
            "    v4 = df['cvss_v4_vector'].notna().sum()\n"
            "    ru = df['d_ru'].notna().sum()\n"
            "    en = df['d_en'].notna().sum()\n"
            "    epss = df['epss'].notna().sum()\n"
            "    kev = (df['kev'].fillna(0) > 0).sum()\n"
            "    expl = (df['exploit'].fillna(0) > 0).sum()\n"
            "    return {\n"
            "        'Размер': n,\n"
            "        'CVSS v3.1': f'{v3:,} ({v3/n:.1%})',\n"
            "        'CVSS v4.0': f'{v4:,} ({v4/n:.1%})',\n"
            "        'Описания d_ru': f'{ru:,} ({ru/n:.1%})',\n"
            "        'Описания d_en': f'{en:,} ({en/n:.1%})',\n"
            "        'EPSS': f'{epss:,} ({epss/n:.1%})',\n"
            "        'CISA KEV': f'{kev:,} ({kev/n:.1%})',\n"
            "        'ExploitDB': f'{expl:,} ({expl/n:.1%})',\n"
            "    }\n"
            "\n"
            "summary = pd.DataFrame({k: split_stats(v) for k, v in splits.items()})\n"
            "summary.index.name = 'Показатель'\n"
            "summary"
        ),
        code(
            "# Сохраняем сводную таблицу в Markdown для копирования в главу 2 ВКР\n"
            "md_path = ROOT / 'reports' / 'dataset_summary.md'\n"
            "md_path.write_text(\n"
            "    '# Сводная статистика датасета\\n\\n' + summary.to_markdown() + '\\n',\n"
            "    encoding='utf-8',\n"
            ")\n"
            "print('Сохранено в', md_path)\n"
            "print()\n"
            "print(summary.to_markdown())"
        ),
        md(
            "## 2. Распределение по источникам (NVD vs БДУ ФСТЭК)\n\n"
            "Записи из БДУ ФСТЭК идентифицируются по префиксу `BDU:`, "
            "записи из NVD — по префиксу `CVE-` в колонке `id`. "
            "(Поле `cve_id` содержит CVE-идентификатор даже у БДУ-записей.)"
        ),
        code(
            "train = splits['train']\n"
            "source = np.where(train['id'].astype(str).str.startswith('BDU'),\n"
            "                  'БДУ ФСТЭК', 'NVD')\n"
            "src_counts = pd.Series(source).value_counts()\n"
            "print(src_counts)\n"
            "\n"
            "fig, ax = plt.subplots(figsize=(6, 6))\n"
            "colors = ['#1f77b4', '#ff7f0e']\n"
            "ax.pie(src_counts.values, labels=src_counts.index, colors=colors,\n"
            "       autopct='%1.1f%%', startangle=90, textprops={'fontsize': 12})\n"
            "ax.set_title('Распределение записей train set по источникам', fontsize=13)\n"
            "fig.savefig(FIG_DIR / 'sources_pie.png')\n"
            "plt.show()"
        ),
        md(
            "## 3. Распределение классов по 12 метрикам CVSS v4.0\n\n"
            "Берём только записи с непустым `cvss_v4_vector` (4 715 / 1 041 / 972 "
            "для train/val/test). Покажет дисбаланс по каждой из 12 метрик."
        ),
        code(
            "from src.data_preparation.cvss_vector_parser import (\n"
            "    V4_METRIC_ORDER, V4_LABEL_MAPS, parse_v4_vector,\n"
            ")\n"
            "\n"
            "def parse_metrics_df(df: pd.DataFrame) -> pd.DataFrame:\n"
            "    rows = []\n"
            "    for vec in df['cvss_v4_vector'].dropna():\n"
            "        try:\n"
            "            rows.append(parse_v4_vector(vec))\n"
            "        except Exception:\n"
            "            continue\n"
            "    return pd.DataFrame(rows)\n"
            "\n"
            "train_v4 = parse_metrics_df(splits['train'])\n"
            "test_v4 = parse_metrics_df(splits['test'])\n"
            "print(f'train v4: {len(train_v4)}, test v4: {len(test_v4)}')\n"
            "train_v4.head()"
        ),
        code(
            "fig, axes = plt.subplots(3, 4, figsize=(18, 11))\n"
            "for ax, metric in zip(axes.flat, V4_METRIC_ORDER):\n"
            "    labels = V4_LABEL_MAPS[metric]\n"
            "    counts = train_v4[metric].value_counts().reindex(labels, fill_value=0)\n"
            "    bars = ax.bar(counts.index, counts.values, color='#4c72b0')\n"
            "    ax.set_title(f'{metric}', fontsize=12, fontweight='bold')\n"
            "    ax.set_ylabel('Кол-во записей')\n"
            "    for bar, val in zip(bars, counts.values):\n"
            "        ax.text(bar.get_x() + bar.get_width()/2, val,\n"
            "                f'{val/counts.sum():.1%}',\n"
            "                ha='center', va='bottom', fontsize=9)\n"
            "fig.suptitle('Распределение классов по 12 метрикам CVSS v4.0 (train set)',\n"
            "             fontsize=14, y=1.00)\n"
            "fig.tight_layout()\n"
            "fig.savefig(FIG_DIR / 'metrics_class_distribution.png')\n"
            "plt.show()"
        ),
        code(
            "# Численная таблица дисбаланса: доля мажоритарного класса по каждой метрике\n"
            "imb = []\n"
            "for metric in V4_METRIC_ORDER:\n"
            "    counts = train_v4[metric].value_counts(normalize=True)\n"
            "    imb.append({\n"
            "        'Метрика': metric,\n"
            "        'Кол-во классов': len(V4_LABEL_MAPS[metric]),\n"
            "        'Доля мажоритарного класса': f'{counts.iloc[0]:.1%}',\n"
            "        'Мажоритарный класс': counts.index[0],\n"
            "    })\n"
            "imb_df = pd.DataFrame(imb)\n"
            "(ROOT / 'reports' / 'class_imbalance.md').write_text(\n"
            "    '# Дисбаланс классов\\n\\n' + imb_df.to_markdown(index=False) + '\\n',\n"
            "    encoding='utf-8',\n"
            ")\n"
            "imb_df"
        ),
        md("## 4. Длины описаний в токенах (en / ru)"),
        code(
            "from src.data_preparation.tokenizer_wrapper import CVSSTokenizer\n"
            "import warnings\n"
            "warnings.filterwarnings('ignore')\n"
            "\n"
            "tok = CVSSTokenizer()\n"
            "\n"
            "def token_lens(series: pd.Series, sample_size: int = 5000) -> np.ndarray:\n"
            "    texts = series.dropna().sample(\n"
            "        min(sample_size, series.dropna().shape[0]), random_state=42\n"
            "    ).tolist()\n"
            "    lens = []\n"
            "    for batch_start in range(0, len(texts), 64):\n"
            "        batch = texts[batch_start:batch_start + 64]\n"
            "        out = tok.tokenize_batch(batch, max_length=512)\n"
            "        lens.extend([sum(m) for m in out['attention_mask']])\n"
            "    return np.array(lens)\n"
            "\n"
            "lens_en = token_lens(splits['train']['d_en'])\n"
            "lens_ru = token_lens(splits['train']['d_ru'])\n"
            "print(f'en: mean={lens_en.mean():.1f}, median={np.median(lens_en):.0f}, p95={np.percentile(lens_en, 95):.0f}')\n"
            "print(f'ru: mean={lens_ru.mean():.1f}, median={np.median(lens_ru):.0f}, p95={np.percentile(lens_ru, 95):.0f}')"
        ),
        code(
            "fig, ax = plt.subplots(figsize=(10, 5))\n"
            "bins = np.linspace(0, 512, 60)\n"
            "ax.hist(lens_en, bins=bins, alpha=0.6, label=f'Английский (n={len(lens_en):,})',\n"
            "        color='#1f77b4')\n"
            "ax.hist(lens_ru, bins=bins, alpha=0.6, label=f'Русский (n={len(lens_ru):,})',\n"
            "        color='#d62728')\n"
            "ax.axvline(512, color='black', linestyle='--', alpha=0.5, label='max_length=512')\n"
            "ax.set_xlabel('Длина в токенах mBERT')\n"
            "ax.set_ylabel('Кол-во описаний')\n"
            "ax.set_title('Распределение длин описаний в токенах (выборка 5 000 из train)')\n"
            "ax.legend()\n"
            "fig.savefig(FIG_DIR / 'token_lengths.png')\n"
            "plt.show()"
        ),
        md("## 5. Итоговые CVSS-баллы и severity"),
        code(
            "from src.cvss_calculator import CVSSCalculator\n"
            "calc = CVSSCalculator()\n"
            "\n"
            "scores = []\n"
            "severities = []\n"
            "for _, row in train_v4.iterrows():\n"
            "    metrics = {m: (row[m] if isinstance(row[m], str) else ('A' if m == 'E' else 'N'))\n"
            "               for m in V4_METRIC_ORDER}\n"
            "    score, sev, _ = calc.calculate(metrics)\n"
            "    scores.append(score)\n"
            "    severities.append(sev)\n"
            "scores = np.array(scores)\n"
            "print(f'mean score = {scores.mean():.2f}, median = {np.median(scores):.2f}')"
        ),
        code(
            "fig, axes = plt.subplots(1, 2, figsize=(15, 5))\n"
            "\n"
            "axes[0].hist(scores, bins=np.arange(0, 10.5, 0.25), color='#4c72b0', edgecolor='white')\n"
            "axes[0].set_xlabel('CVSS-балл')\n"
            "axes[0].set_ylabel('Кол-во записей')\n"
            "axes[0].set_title('Распределение итоговых CVSS-баллов на train (v4.0)')\n"
            "axes[0].axvline(scores.mean(), color='red', linestyle='--', label=f'mean={scores.mean():.2f}')\n"
            "axes[0].legend()\n"
            "\n"
            "sev_order = ['None', 'Low', 'Medium', 'High', 'Critical']\n"
            "sev_colors = ['#6c757d', '#28a745', '#ffc107', '#fd7e14', '#dc3545']\n"
            "sev_counts = pd.Series(severities).value_counts().reindex(sev_order, fill_value=0)\n"
            "bars = axes[1].bar(sev_counts.index, sev_counts.values, color=sev_colors,\n"
            "                   edgecolor='black')\n"
            "for bar, val in zip(bars, sev_counts.values):\n"
            "    axes[1].text(bar.get_x() + bar.get_width()/2, val,\n"
            "                 f'{val}\\n({val/sev_counts.sum():.1%})',\n"
            "                 ha='center', va='bottom', fontsize=10)\n"
            "axes[1].set_xlabel('Уровень критичности')\n"
            "axes[1].set_ylabel('Кол-во записей')\n"
            "axes[1].set_title('Распределение severity на train (v4.0)')\n"
            "\n"
            "fig.tight_layout()\n"
            "fig.savefig(FIG_DIR / 'score_severity_distribution.png')\n"
            "plt.show()"
        ),
        md("## 6. Топ-20 наиболее частых CWE в train set"),
        code(
            "cwe_counts = splits['train']['cwe_id'].value_counts().head(20)\n"
            "cwe_names = (splits['train'][['cwe_id', 'cwe_name']]\n"
            "             .drop_duplicates('cwe_id')\n"
            "             .set_index('cwe_id')['cwe_name'])\n"
            "\n"
            "fig, ax = plt.subplots(figsize=(11, 8))\n"
            "labels = []\n"
            "for cwe in cwe_counts.index:\n"
            "    nm = str(cwe_names.get(cwe, ''))[:55]\n"
            "    labels.append(f'{cwe} — {nm}')\n"
            "y = np.arange(len(cwe_counts))[::-1]\n"
            "bars = ax.barh(y, cwe_counts.values, color='#4c72b0')\n"
            "ax.set_yticks(y)\n"
            "ax.set_yticklabels(labels, fontsize=9)\n"
            "ax.set_xlabel('Кол-во записей в train')\n"
            "ax.set_title('Топ-20 наиболее частых CWE')\n"
            "for bar, val in zip(bars, cwe_counts.values):\n"
            "    ax.text(val, bar.get_y() + bar.get_height()/2, f' {val:,}',\n"
            "            va='center', fontsize=9)\n"
            "fig.tight_layout()\n"
            "fig.savefig(FIG_DIR / 'top20_cwe.png')\n"
            "plt.show()"
        ),
        md(
            "## 7. Корреляции между 11 базовыми метриками v4.0\n\n"
            "Используем Cramer's V — мера ассоциации для категориальных величин "
            "(0 → независимы, 1 → полная зависимость). E (Exploit Maturity) "
            "исключаем — это эксплойт-метрика, а не базовая."
        ),
        code(
            "from scipy.stats import chi2_contingency\n"
            "\n"
            "def cramers_v(x, y):\n"
            "    table = pd.crosstab(x, y).values\n"
            "    chi2 = chi2_contingency(table, correction=False)[0]\n"
            "    n = table.sum()\n"
            "    r, k = table.shape\n"
            "    return float(np.sqrt(chi2 / (n * (min(r, k) - 1)))) if min(r, k) > 1 else 0.0\n"
            "\n"
            "base = [m for m in V4_METRIC_ORDER if m != 'E']\n"
            "mat = pd.DataFrame(0.0, index=base, columns=base)\n"
            "for a in base:\n"
            "    for b in base:\n"
            "        if a == b:\n"
            "            mat.loc[a, b] = 1.0\n"
            "        else:\n"
            "            mat.loc[a, b] = cramers_v(train_v4[a], train_v4[b])\n"
            "mat.round(2)"
        ),
        code(
            "fig, ax = plt.subplots(figsize=(9, 7))\n"
            "sns.heatmap(mat.astype(float), annot=True, fmt='.2f', cmap='YlOrRd',\n"
            "            vmin=0, vmax=1, ax=ax, square=True, cbar_kws={'label': \"Cramer's V\"})\n"
            "ax.set_title('Корреляции между 11 базовыми метриками CVSS v4.0 (Cramer\\'s V)')\n"
            "fig.tight_layout()\n"
            "fig.savefig(FIG_DIR / 'metric_correlations.png')\n"
            "plt.show()"
        ),
        md(
            "## Итог: Markdown-сводка для главы 2 ВКР\n\n"
            "Сохранили `reports/dataset_summary.md` и `reports/class_imbalance.md`. "
            "Графики — в `reports/figures/dataset/`."
        ),
        code(
            "print('Создано:')\n"
            "for f in sorted(FIG_DIR.glob('*.png')):\n"
            "    print(' •', f.relative_to(ROOT))\n"
            "print(' •', (ROOT / 'reports' / 'dataset_summary.md').relative_to(ROOT))\n"
            "print(' •', (ROOT / 'reports' / 'class_imbalance.md').relative_to(ROOT))"
        ),
    ]
    return write_notebook("09_data_exploration.ipynb", cells)


# =============================================================== Notebook 10
def build_10() -> Path:
    cells = [
        md(
            "# 10 — Анализ ошибок модели (Глава 3 ВКР)\n\n"
            "Раздел 3.6 ВКР: анализ ошибок по типам, per-CWE, по уверенности, "
            "по уровням severity. Используем `VulnerabilityPredictor` для прогона "
            "по всем 972 записям test set с CVSS v4.0.\n\n"
            "### Артефакты\n"
            "- `reports/error_analysis/worst_cases.csv`\n"
            "- `reports/error_analysis/per_cwe_metrics.csv`\n"
            "- `reports/severity_transitions.csv`\n"
            "- `reports/figures/per_cwe_analysis.png`\n"
            "- `reports/figures/confidence_analysis.png`\n"
        ),
        code(
            "from pathlib import Path\n"
            "import sys\n"
            "import json\n"
            "\n"
            "import numpy as np\n"
            "import pandas as pd\n"
            "import matplotlib.pyplot as plt\n"
            "import seaborn as sns\n"
            "\n"
            "ROOT = Path.cwd()\n"
            "if ROOT.name == 'notebooks':\n"
            "    ROOT = ROOT.parent\n"
            "sys.path.insert(0, str(ROOT))\n"
            "\n"
            "plt.rcParams['font.family'] = 'DejaVu Sans'\n"
            "plt.rcParams['savefig.dpi'] = 300\n"
            "plt.rcParams['savefig.bbox'] = 'tight'\n"
            "\n"
            "FIG_DIR = ROOT / 'reports' / 'figures'\n"
            "ERR_DIR = ROOT / 'reports' / 'error_analysis'\n"
            "ERR_DIR.mkdir(parents=True, exist_ok=True)"
        ),
        md("## 1. Прогон модели по test set"),
        code(
            "from src.inference import VulnerabilityPredictor\n"
            "from src.data_preparation.cvss_vector_parser import (\n"
            "    V4_METRIC_ORDER, V4_LABEL_MAPS, parse_v4_vector,\n"
            ")\n"
            "\n"
            "predictor = VulnerabilityPredictor(\n"
            "    model_path=str(ROOT / 'models' / 'final_model.pt'),\n"
            "    config_path=str(ROOT / 'configs' / 'train.yaml'),\n"
            "    cwe_vocab_path=str(ROOT / 'data' / 'processed' / 'cwe_vocab.json'),\n"
            "    device='cpu',\n"
            ")\n"
            "test_df = pd.read_parquet(ROOT / 'data' / 'processed' / 'test.parquet')\n"
            "test_v4 = test_df[test_df['cvss_v4_vector'].notna()].reset_index(drop=True)\n"
            "print(f'Test v4: {len(test_v4)} записей')"
        ),
        code(
            "items = []\n"
            "for _, r in test_v4.iterrows():\n"
            "    items.append({\n"
            "        'description': r['d_ru'] if pd.notna(r['d_ru']) else r['d_en'],\n"
            "        'description_ru': r['d_ru'] if pd.notna(r['d_ru']) else None,\n"
            "        'cwe_id': r['cwe_id'],\n"
            "        'epss': float(r['epss']) if pd.notna(r['epss']) else None,\n"
            "        'kev': int(r['kev']) if pd.notna(r['kev']) else None,\n"
            "        'exploit': int(r['exploit']) if pd.notna(r['exploit']) else None,\n"
            "    })\n"
            "\n"
            "import time\n"
            "t0 = time.time()\n"
            "predictions = predictor.predict_batch(items, batch_size=16)\n"
            "print(f'Inference time: {time.time() - t0:.1f} сек')"
        ),
        code(
            "BASE_METRICS = [m for m in V4_METRIC_ORDER if m != 'E']\n"
            "\n"
            "rows = []\n"
            "for r, pred in zip(test_v4.itertuples(), predictions):\n"
            "    true_metrics = parse_v4_vector(r.cvss_v4_vector)\n"
            "    n_correct = sum(true_metrics[m] == pred['metrics'][m] for m in BASE_METRICS)\n"
            "    conf_avg = float(np.mean([pred['confidence'][m] for m in V4_METRIC_ORDER]))\n"
            "    rows.append({\n"
            "        'cve_id': r.cve_id,\n"
            "        'cwe_id': r.cwe_id,\n"
            "        'description': (r.d_ru if isinstance(r.d_ru, str) and r.d_ru else r.d_en) or '',\n"
            "        'true_vector': r.cvss_v4_vector.split('/CR:')[0],\n"
            "        'pred_vector': pred['vector'],\n"
            "        'true_score': None,\n"
            "        'pred_score': pred['score'],\n"
            "        'true_severity': None,\n"
            "        'pred_severity': pred['severity'],\n"
            "        'num_metrics_correct': n_correct,\n"
            "        'confidence_avg': conf_avg,\n"
            "        **{f'true_{m}': true_metrics[m] for m in V4_METRIC_ORDER},\n"
            "        **{f'pred_{m}': pred['metrics'][m] for m in V4_METRIC_ORDER},\n"
            "        **{f'conf_{m}': pred['confidence'][m] for m in V4_METRIC_ORDER},\n"
            "    })\n"
            "results = pd.DataFrame(rows)\n"
            "\n"
            "from src.cvss_calculator import CVSSCalculator\n"
            "calc = CVSSCalculator()\n"
            "for i, row in results.iterrows():\n"
            "    metrics = {\n"
            "        m: (row[f'true_{m}'] if isinstance(row[f'true_{m}'], str)\n"
            "            else ('A' if m == 'E' else 'N'))\n"
            "        for m in V4_METRIC_ORDER\n"
            "    }\n"
            "    s, sev, _ = calc.calculate(metrics)\n"
            "    results.at[i, 'true_score'] = s\n"
            "    results.at[i, 'true_severity'] = sev\n"
            "\n"
            "results['score_abs_error'] = (results['pred_score'] - results['true_score']).abs()\n"
            "print('Shape:', results.shape)\n"
            "print(f'mean num_metrics_correct = {results.num_metrics_correct.mean():.2f} / 11')\n"
            "print(f'mean score MAE = {results.score_abs_error.mean():.2f}')\n"
            "results.head()"
        ),
        md(
            "## Раздел 1. Худшие предсказания по числу неверных метрик\n\n"
            "Топ-20 записей с минимальным `num_metrics_correct`. "
            "Сохраняем в `reports/error_analysis/worst_cases.csv` "
            "для приложения к ВКР."
        ),
        code(
            "worst = results.nsmallest(20, 'num_metrics_correct')[\n"
            "    ['cve_id', 'cwe_id', 'description', 'true_vector', 'pred_vector',\n"
            "     'num_metrics_correct', 'true_score', 'pred_score',\n"
            "     'true_severity', 'pred_severity', 'confidence_avg']\n"
            "].copy()\n"
            "worst['description'] = worst['description'].str.slice(0, 200)\n"
            "worst.to_csv(ERR_DIR / 'worst_cases.csv', index=False, encoding='utf-8-sig')\n"
            "worst.head(10)"
        ),
        code(
            "# Какие именно метрики ошибаются у худших случаев?\n"
            "diff = []\n"
            "for _, row in results.nsmallest(50, 'num_metrics_correct').iterrows():\n"
            "    for m in BASE_METRICS:\n"
            "        if row[f'true_{m}'] != row[f'pred_{m}']:\n"
            "            diff.append(m)\n"
            "wrong_metric_counts = pd.Series(diff).value_counts()\n"
            "print('Какие метрики чаще всего ошибаются в худших 50 случаях:')\n"
            "print(wrong_metric_counts)"
        ),
        md("## Раздел 2. Per-CWE анализ"),
        code(
            "min_count = 10\n"
            "cwe_counts = results['cwe_id'].value_counts()\n"
            "good_cwe = cwe_counts[cwe_counts >= min_count].index.tolist()\n"
            "per_cwe = (results[results['cwe_id'].isin(good_cwe)]\n"
            "           .groupby('cwe_id')\n"
            "           .agg(n=('cve_id', 'count'),\n"
            "                mean_correct=('num_metrics_correct', 'mean'),\n"
            "                score_mae=('score_abs_error', 'mean'),\n"
            "                accuracy=('num_metrics_correct', lambda s: (s == 11).mean()))\n"
            "           .sort_values('mean_correct', ascending=False))\n"
            "per_cwe.round(3).to_csv(ERR_DIR / 'per_cwe_metrics.csv', encoding='utf-8-sig')\n"
            "print(f'CWE с ≥{min_count} примерами: {len(per_cwe)}')\n"
            "print('\\nTop-10 best:')\n"
            "print(per_cwe.head(10).round(3).to_string())\n"
            "print('\\nTop-10 worst:')\n"
            "print(per_cwe.tail(10).round(3).to_string())"
        ),
        code(
            "top20 = cwe_counts.head(20).index.tolist()\n"
            "subset = per_cwe.loc[per_cwe.index.intersection(top20)].sort_values('mean_correct')\n"
            "\n"
            "fig, ax = plt.subplots(figsize=(11, 8))\n"
            "y = np.arange(len(subset))\n"
            "bars = ax.barh(y, subset['mean_correct'], color='#4c72b0')\n"
            "ax.set_yticks(y)\n"
            "ax.set_yticklabels([f'{c} (n={int(subset.loc[c, \"n\"])})' for c in subset.index])\n"
            "ax.set_xlabel('Среднее число правильных метрик из 11')\n"
            "ax.set_title('Качество предсказания по 20 наиболее частым CWE в test set')\n"
            "ax.axvline(results.num_metrics_correct.mean(), color='red', linestyle='--',\n"
            "           label=f'Общее среднее = {results.num_metrics_correct.mean():.2f}')\n"
            "ax.legend()\n"
            "for bar, val in zip(bars, subset['mean_correct']):\n"
            "    ax.text(val, bar.get_y() + bar.get_height()/2, f' {val:.2f}',\n"
            "            va='center', fontsize=9)\n"
            "fig.tight_layout()\n"
            "fig.savefig(FIG_DIR / 'per_cwe_analysis.png')\n"
            "plt.show()"
        ),
        md("## Раздел 3. Анализ confidence модели"),
        code(
            "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
            "\n"
            "# (а) корреляция средней уверенности с числом правильных метрик\n"
            "buckets = pd.cut(results['confidence_avg'],\n"
            "                 bins=np.arange(0.5, 1.01, 0.05))\n"
            "calibration = results.groupby(buckets, observed=True).agg(\n"
            "    accuracy=('num_metrics_correct', 'mean'),\n"
            "    n=('cve_id', 'count'),\n"
            ").dropna()\n"
            "x_centers = [(b.left + b.right) / 2 for b in calibration.index]\n"
            "axes[0].scatter(x_centers, calibration['accuracy'] / 11,\n"
            "                s=calibration['n'] * 3, alpha=0.6, color='#1f77b4')\n"
            "for xc, ac, n in zip(x_centers, calibration['accuracy'] / 11, calibration['n']):\n"
            "    axes[0].annotate(f'n={n}', (xc, ac), fontsize=8,\n"
            "                     textcoords='offset points', xytext=(0, 5))\n"
            "axes[0].plot([0.5, 1.0], [0.5, 1.0], 'k--', alpha=0.4, label='Идеальная калибровка')\n"
            "axes[0].set_xlabel('Средняя уверенность модели по 12 метрикам')\n"
            "axes[0].set_ylabel('Точность (доля верных метрик)')\n"
            "axes[0].set_title('Калибровка confidence')\n"
            "axes[0].legend()\n"
            "axes[0].set_xlim(0.5, 1.0)\n"
            "axes[0].set_ylim(0.5, 1.0)\n"
            "\n"
            "# (б) распределение confidence для верных/неверных метрик\n"
            "right_confs = []\n"
            "wrong_confs = []\n"
            "for _, row in results.iterrows():\n"
            "    for m in BASE_METRICS:\n"
            "        c = row[f'conf_{m}']\n"
            "        if row[f'true_{m}'] == row[f'pred_{m}']:\n"
            "            right_confs.append(c)\n"
            "        else:\n"
            "            wrong_confs.append(c)\n"
            "axes[1].hist(right_confs, bins=30, alpha=0.6,\n"
            "             label=f'Верно ({len(right_confs):,})', color='#28a745', density=True)\n"
            "axes[1].hist(wrong_confs, bins=30, alpha=0.6,\n"
            "             label=f'Неверно ({len(wrong_confs):,})', color='#dc3545', density=True)\n"
            "axes[1].set_xlabel('Confidence (softmax)')\n"
            "axes[1].set_ylabel('Плотность')\n"
            "axes[1].set_title('Распределение confidence: верные vs неверные предсказания')\n"
            "axes[1].legend()\n"
            "\n"
            "fig.tight_layout()\n"
            "fig.savefig(FIG_DIR / 'confidence_analysis.png')\n"
            "plt.show()\n"
            "\n"
            "import numpy as np\n"
            "print(f'Средний confidence на верных: {np.mean(right_confs):.3f}')\n"
            "print(f'Средний confidence на неверных: {np.mean(wrong_confs):.3f}')"
        ),
        code(
            "# Топ-10 уверенных, но неверных предсказаний (confidence > 0.9)\n"
            "high_conf_wrong = []\n"
            "for _, row in results.iterrows():\n"
            "    for m in BASE_METRICS:\n"
            "        if row[f'true_{m}'] != row[f'pred_{m}'] and row[f'conf_{m}'] > 0.9:\n"
            "            high_conf_wrong.append({\n"
            "                'cve_id': row['cve_id'], 'cwe_id': row['cwe_id'],\n"
            "                'metric': m, 'true': row[f'true_{m}'],\n"
            "                'pred': row[f'pred_{m}'], 'confidence': row[f'conf_{m}'],\n"
            "                'description': row['description'][:200],\n"
            "            })\n"
            "high_conf_wrong = pd.DataFrame(high_conf_wrong).sort_values(\n"
            "    'confidence', ascending=False\n"
            ").head(10)\n"
            "high_conf_wrong.to_csv(ERR_DIR / 'high_confidence_errors.csv',\n"
            "                       index=False, encoding='utf-8-sig')\n"
            "print(f'Всего ошибок с confidence > 0.9: {((results.iloc[:, results.columns.str.startswith(\"conf_\")]).values > 0.9).sum()}')\n"
            "high_conf_wrong[['cve_id', 'metric', 'true', 'pred', 'confidence']]"
        ),
        md(
            "## Раздел 4. Анализ severity-ошибок\n\n"
            "Какие переходы `true → pred` встречаются чаще всего."
        ),
        code(
            "with open(ROOT / 'reports' / 'test_evaluation.json', 'r', encoding='utf-8') as f:\n"
            "    eval_data = json.load(f)\n"
            "sev_conf = eval_data['severity_confusion']\n"
            "\n"
            "transitions = []\n"
            "for true_sev, preds in sev_conf.items():\n"
            "    for pred_sev, n in preds.items():\n"
            "        if n > 0:\n"
            "            transitions.append({\n"
            "                'true': true_sev, 'pred': pred_sev, 'count': n,\n"
            "                'type': ('exact' if true_sev == pred_sev\n"
            "                          else 'overestimate' if ['None','Low','Medium','High','Critical'].index(pred_sev) >\n"
            "                                ['None','Low','Medium','High','Critical'].index(true_sev)\n"
            "                          else 'underestimate'),\n"
            "            })\n"
            "trans_df = pd.DataFrame(transitions).sort_values('count', ascending=False)\n"
            "trans_df.to_csv(ROOT / 'reports' / 'severity_transitions.csv',\n"
            "                index=False, encoding='utf-8-sig')\n"
            "trans_df"
        ),
        code(
            "# Краткая статистика смещений severity\n"
            "tot = trans_df['count'].sum()\n"
            "exact = trans_df[trans_df['type'] == 'exact']['count'].sum()\n"
            "over = trans_df[trans_df['type'] == 'overestimate']['count'].sum()\n"
            "under = trans_df[trans_df['type'] == 'underestimate']['count'].sum()\n"
            "print(f'Точные предсказания severity: {exact}/{tot} ({exact/tot:.1%})')\n"
            "print(f'Завышения (overestimate):    {over}/{tot} ({over/tot:.1%})')\n"
            "print(f'Занижения (underestimate):   {under}/{tot} ({under/tot:.1%})')\n"
            "print('\\nКрупнейшие переходы:')\n"
            "for _, r in trans_df.head(8).iterrows():\n"
            "    arrow = '→' if r['type'] != 'exact' else '='\n"
            '    print(f\'  {r.true:>8} {arrow} {r.pred:<8}  {r["count"]:>4}  ({r["type"]})\')'
        ),
        code(
            "# Сохраняем DataFrame с полными результатами для ноутбука 11\n"
            "results.to_parquet(ERR_DIR / 'test_predictions.parquet', index=False)\n"
            "print('Сохранено:', ERR_DIR / 'test_predictions.parquet')\n"
            "print('\\nСоздано:')\n"
            "for f in sorted(ERR_DIR.glob('*')):\n"
            "    print(' •', f.relative_to(ROOT))\n"
            "print(' •', (FIG_DIR / 'per_cwe_analysis.png').relative_to(ROOT))\n"
            "print(' •', (FIG_DIR / 'confidence_analysis.png').relative_to(ROOT))\n"
            "print(' •', (ROOT / 'reports' / 'severity_transitions.csv').relative_to(ROOT))"
        ),
    ]
    return write_notebook("10_error_analysis.ipynb", cells)


# =============================================================== Notebook 11
def build_11() -> Path:
    cells = [
        md(
            "# 11 — Итоговая сводка результатов (Глава 3 ВКР)\n\n"
            "Финальные таблицы для разделов 3.2, 3.3, 3.5, 3.7 ВКР. "
            "Все значения берём из `reports/test_evaluation.json` (test set, "
            "972 v4.0-записи) и из метрик последней эпохи Stage 2 (записаны "
            "вручную в ноутбуке `04_evaluation.ipynb`)."
        ),
        code(
            "from pathlib import Path\n"
            "import sys\n"
            "import json\n"
            "\n"
            "import pandas as pd\n"
            "\n"
            "ROOT = Path.cwd()\n"
            "if ROOT.name == 'notebooks':\n"
            "    ROOT = ROOT.parent\n"
            "sys.path.insert(0, str(ROOT))\n"
            "\n"
            "with open(ROOT / 'reports' / 'test_evaluation.json', 'r', encoding='utf-8') as fh:\n"
            "    data = json.load(fh)\n"
            "agg = data['aggregated']\n"
            "per_metric = data['per_metric']"
        ),
        md("## Раздел 1. Итоговые метрики качества (для раздела 3.2 ВКР)"),
        code(
            "summary = pd.DataFrame([\n"
            "    ('Macro-F1 (12 метрик)',          f\"{agg['macro_f1']:.4f}\"),\n"
            "    ('Vector Accuracy (11 метрик)',   f\"{agg['vector_accuracy']:.4f}\"),\n"
            "    ('Среднее число правильных метрик',\n"
            "         f\"{agg['metrics_correct_avg']:.2f} / 11 ({agg['metrics_correct_avg']/11:.1%})\"),\n"
            "    ('MAE по CVSS-баллу',            f\"{agg['score_mae']:.2f} ({agg['score_mae']/10:.1%} шкалы)\"),\n"
            "    ('RMSE по CVSS-баллу',           f\"{agg['score_rmse']:.2f}\"),\n"
            "    ('Severity Accuracy',            f\"{agg['severity_accuracy']:.4f}\"),\n"
            "    ('Severity Within ±1',           f\"{agg['severity_within_one']:.4f}\"),\n"
            "    ('Размер test set',              f\"{agg['samples_evaluated']} CVSS v4.0 записей\"),\n"
            "], columns=['Показатель', 'Значение'])\n"
            "(ROOT / 'reports' / 'final_summary.md').write_text(\n"
            "    '# Итоговые метрики качества (test set)\\n\\n' +\n"
            "    summary.to_markdown(index=False) + '\\n',\n"
            "    encoding='utf-8',\n"
            ")\n"
            "summary"
        ),
        md("## Раздел 2. Per-metric F1 / Accuracy (для раздела 3.3 ВКР)"),
        code(
            "FULL_NAMES = {\n"
            "    'AV': 'Attack Vector',\n"
            "    'AC': 'Attack Complexity',\n"
            "    'AT': 'Attack Requirements',\n"
            "    'PR': 'Privileges Required',\n"
            "    'UI': 'User Interaction',\n"
            "    'VC': 'Vulnerable System Confidentiality',\n"
            "    'VI': 'Vulnerable System Integrity',\n"
            "    'VA': 'Vulnerable System Availability',\n"
            "    'SC': 'Subsequent System Confidentiality',\n"
            "    'SI': 'Subsequent System Integrity',\n"
            "    'SA': 'Subsequent System Availability',\n"
            "    'E':  'Exploit Maturity',\n"
            "}\n"
            "per_metric_df = pd.DataFrame([\n"
            "    {\n"
            "        'Метрика': m,\n"
            "        'Полное название': FULL_NAMES[m],\n"
            "        'F1 (macro)': round(per_metric[m]['f1_macro'], 4),\n"
            "        'Accuracy': round(per_metric[m]['accuracy'], 4),\n"
            "        'Support': per_metric[m]['support'],\n"
            "    }\n"
            "    for m in FULL_NAMES\n"
            "])\n"
            "(ROOT / 'reports' / 'per_metric_summary.md').write_text(\n"
            "    '# Per-metric F1 / Accuracy на test set\\n\\n' +\n"
            "    per_metric_df.to_markdown(index=False) + '\\n',\n"
            "    encoding='utf-8',\n"
            ")\n"
            "per_metric_df"
        ),
        md("## Раздел 3. Стабильность модели — val vs test (для раздела 3.5 ВКР)"),
        code(
            "# F1 на val на последней эпохе Stage 2 (взято из логов обучения,\n"
            "# дублирует значения из notebooks/04_evaluation.ipynb)\n"
            "val_metrics_stage2 = {\n"
            "    'AV': 0.534, 'AC': 0.724, 'AT': 0.744, 'PR': 0.629,\n"
            "    'UI': 0.629, 'VC': 0.805, 'VI': 0.813, 'VA': 0.823,\n"
            "    'SC': 0.648, 'SI': 0.635, 'SA': 0.660, 'E':  0.881,\n"
            "}\n"
            "stability = pd.DataFrame([\n"
            "    {\n"
            "        'Метрика': m,\n"
            "        'F1 val (epoch 18)': round(val_metrics_stage2[m], 3),\n"
            "        'F1 test': round(per_metric[m]['f1_macro'], 3),\n"
            "        'Δ': round(per_metric[m]['f1_macro'] - val_metrics_stage2[m], 3),\n"
            "    }\n"
            "    for m in val_metrics_stage2\n"
            "])\n"
            "(ROOT / 'reports' / 'stability_val_vs_test.md').write_text(\n"
            "    '# Стабильность модели: val vs test\\n\\n' +\n"
            "    stability.to_markdown(index=False) + '\\n',\n"
            "    encoding='utf-8',\n"
            ")\n"
            "stability"
        ),
        md("## Раздел 4. Финальная Markdown-сводка"),
        code(
            "final_md = '\\n\\n'.join([\n"
            "    '# Итоговые результаты экспериментов\\n',\n"
            "    '## Интегральные метрики качества\\n',\n"
            "    summary.to_markdown(index=False),\n"
            "    '## Per-metric качество (test set)\\n',\n"
            "    per_metric_df.to_markdown(index=False),\n"
            "    '## Стабильность: val vs test\\n',\n"
            "    stability.to_markdown(index=False),\n"
            "])\n"
            "(ROOT / 'reports' / 'final_results.md').write_text(final_md, encoding='utf-8')\n"
            "print('Сохранено в reports/final_results.md')"
        ),
        md(
            "## Раздел 5. Показательные примеры для приложения к ВКР\n\n"
            "Берём `reports/error_analysis/test_predictions.parquet` "
            "(создан в ноутбуке 10) и выбираем:\n"
            "- 2 примера с идеальным предсказанием (11/11 метрик),\n"
            "- 2 примера с частичными ошибками (8–9 / 11),\n"
            "- 1 пример с сильной ошибкой (< 6 / 11).\n\n"
            "Для каждого даётся true_vector, pred_vector, средняя уверенность "
            "и разбор низкоконфидентных метрик."
        ),
        code(
            "PRED_PATH = ROOT / 'reports' / 'error_analysis' / 'test_predictions.parquet'\n"
            "if not PRED_PATH.exists():\n"
            "    raise FileNotFoundError(\n"
            "        f'Сначала прогоните notebook 10_error_analysis.ipynb — '\n"
            "        f'нет файла {PRED_PATH}'\n"
            "    )\n"
            "preds = pd.read_parquet(PRED_PATH)\n"
            "print('Загружено предсказаний:', len(preds))\n"
            "preds[['cve_id', 'cwe_id', 'num_metrics_correct', 'true_severity',\n"
            "       'pred_severity', 'confidence_avg']].head()"
        ),
        code(
            "from src.data_preparation.cvss_vector_parser import V4_METRIC_ORDER\n"
            "BASE = [m for m in V4_METRIC_ORDER if m != 'E']\n"
            "\n"
            "def pick(df, n_correct_eq=None, n_correct_lt=None, n_correct_ge=None, n=1, seed=42):\n"
            "    sub = df.copy()\n"
            "    if n_correct_eq is not None:\n"
            "        sub = sub[sub.num_metrics_correct == n_correct_eq]\n"
            "    if n_correct_lt is not None:\n"
            "        sub = sub[sub.num_metrics_correct < n_correct_lt]\n"
            "    if n_correct_ge is not None:\n"
            "        sub = sub[sub.num_metrics_correct >= n_correct_ge]\n"
            "    sub = sub[sub.description.str.len() > 80]\n"
            "    return sub.sample(n=min(n, len(sub)), random_state=seed)\n"
            "\n"
            "perfect = pick(preds, n_correct_eq=11, n=2, seed=42)\n"
            "partial = pick(preds[(preds.num_metrics_correct >= 8) & (preds.num_metrics_correct <= 9)], n=2, seed=123)\n"
            "bad = pick(preds, n_correct_lt=6, n=1, seed=7)\n"
            "showcase = pd.concat([perfect, partial, bad]).reset_index(drop=True)\n"
            "showcase[['cve_id', 'cwe_id', 'num_metrics_correct',\n"
            "          'true_severity', 'pred_severity', 'true_score', 'pred_score']]"
        ),
        code(
            "lines = ['# Показательные примеры предсказаний (приложение к ВКР)\\n']\n"
            "category_names = [\n"
            "    'Идеальное предсказание (11/11 метрик)',\n"
            "    'Идеальное предсказание (11/11 метрик)',\n"
            "    'Частичная ошибка (8–9 / 11 метрик)',\n"
            "    'Частичная ошибка (8–9 / 11 метрик)',\n"
            "    'Грубая ошибка (< 6 / 11 метрик)',\n"
            "]\n"
            "for idx, row in showcase.iterrows():\n"
            "    cat = category_names[idx] if idx < len(category_names) else 'Прочее'\n"
            "    lines.append(f'## Пример {idx+1}. {cat}\\n')\n"
            "    lines.append(f'- **CVE:** {row.cve_id}')\n"
            "    lines.append(f'- **CWE:** {row.cwe_id}')\n"
            "    lines.append(f'- **Severity:** true = {row.true_severity}, pred = {row.pred_severity}')\n"
            "    lines.append(f'- **Score:** true = {row.true_score:.1f}, pred = {row.pred_score:.1f}')\n"
            "    lines.append(f'- **Метрик правильно:** {int(row.num_metrics_correct)} / 11')\n"
            "    lines.append(f'- **Средняя уверенность:** {row.confidence_avg:.3f}')\n"
            "    lines.append('')\n"
            "    lines.append('**Описание:**')\n"
            "    lines.append('')\n"
            "    desc = str(row.description).strip()\n"
            '    lines.append(f\'> {desc[:600]}{"…" if len(desc) > 600 else ""}\')\n'
            "    lines.append('')\n"
            "    lines.append(f'**True vector:** `{row.true_vector}`  \\n**Pred vector:** `{row.pred_vector}`')\n"
            "    lines.append('')\n"
            "    wrong = []\n"
            "    for m in BASE:\n"
            "        if row[f'true_{m}'] != row[f'pred_{m}']:\n"
            "            wrong.append(\n"
            "                f'  - **{m}:** true=`{row[f\"true_{m}\"]}`, '\n"
            '                f\'pred=`{row[f"pred_{m}"]}` (confidence={row[f"conf_{m}"]:.3f})\'\n'
            "            )\n"
            "    if wrong:\n"
            "        lines.append('**Ошибки модели:**')\n"
            "        lines.extend(wrong)\n"
            "    else:\n"
            "        lines.append('**Ошибок нет** — модель попала во все 11 базовых метрик.')\n"
            "    lines.append('')\n"
            "    low = [m for m in V4_METRIC_ORDER if row[f'conf_{m}'] < 0.7]\n"
            "    if low:\n"
            "        lines.append(f'**Низкая уверенность** (<0.7): {\", \".join(low)}')\n"
            "    lines.append('')\n"
            "    lines.append('---\\n')\n"
            "\n"
            "showcase_md = '\\n'.join(lines)\n"
            "(ROOT / 'reports' / 'showcase_examples.md').write_text(showcase_md, encoding='utf-8')\n"
            "print('Сохранено в reports/showcase_examples.md ({} символов)'.format(len(showcase_md)))"
        ),
        code(
            "print('Создано:')\n"
            "for f in ['final_summary.md', 'per_metric_summary.md',\n"
            "         'stability_val_vs_test.md', 'final_results.md',\n"
            "         'showcase_examples.md']:\n"
            "    p = ROOT / 'reports' / f\n"
            "    print(f' • {p.relative_to(ROOT)} ({p.stat().st_size} байт)')"
        ),
    ]
    return write_notebook("11_final_results.ipynb", cells)


if __name__ == "__main__":
    paths = [build_09(), build_10(), build_11()]
    for p in paths:
        print(p)
